# Generated by Django 5.2.4 on 2025-08-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0052_alter_authorentriesplugin_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorentriesplugin',
            name='template_folder',
            field=models.CharField(choices=[('plugins', 'Default template'), ('grid_plugins', 'Grid layout'), ('grid_no_teaser_plugins', 'Grid layout without teaser'), ('internally_celled_grid_no_teaser_plugins', 'Internally celled grid layout without teaser'), ('internally_celled_grid_no_teaser_plugins_htmx', 'Internally celled grid layout without teaser with htmx')], default='plugins', help_text='Select plugin layout to load for this instance', max_length=200, verbose_name='Plugin layout'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogcategorytranslation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogconfig',
            name='url_patterns',
            field=models.CharField(blank=True, choices=[('full_date', 'Full date'), ('short_date', 'Year /  Month'), ('category', 'Category')], default='full_date', max_length=12, verbose_name='Permalink structure'),
        ),
        migrations.AlterField(
            model_name='blogconfigtranslation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='featuredpostsplugin',
            name='template_folder',
            field=models.CharField(choices=[('plugins', 'Default template'), ('grid_plugins', 'Grid layout'), ('grid_no_teaser_plugins', 'Grid layout without teaser'), ('internally_celled_grid_no_teaser_plugins', 'Internally celled grid layout without teaser'), ('internally_celled_grid_no_teaser_plugins_htmx', 'Internally celled grid layout without teaser with htmx')], default='plugins', help_text='Select plugin layout to load for this instance', max_length=200, verbose_name='Plugin layout'),
        ),
        migrations.AlterField(
            model_name='genericblogplugin',
            name='template_folder',
            field=models.CharField(choices=[('plugins', 'Default template'), ('grid_plugins', 'Grid layout'), ('grid_no_teaser_plugins', 'Grid layout without teaser'), ('internally_celled_grid_no_teaser_plugins', 'Internally celled grid layout without teaser'), ('internally_celled_grid_no_teaser_plugins_htmx', 'Internally celled grid layout without teaser with htmx')], default='plugins', help_text='Select plugin layout to load for this instance', max_length=200, verbose_name='Plugin layout'),
        ),
        migrations.AlterField(
            model_name='latestpostsplugin',
            name='template_folder',
            field=models.CharField(choices=[('plugins', 'Default template'), ('grid_plugins', 'Grid layout'), ('grid_no_teaser_plugins', 'Grid layout without teaser'), ('internally_celled_grid_no_teaser_plugins', 'Internally celled grid layout without teaser'), ('internally_celled_grid_no_teaser_plugins_htmx', 'Internally celled grid layout without teaser with htmx')], default='plugins', help_text='Select plugin layout to load for this instance', max_length=200, verbose_name='Plugin layout'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
