# Generated by Django 5.2.4 on 2025-08-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_stories', '0003_alter_post_options_alter_postcontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storiesconfig',
            name='url_patterns',
            field=models.CharField(blank=True, choices=[('full_date', 'Full date'), ('short_date', 'Year /  Month'), ('category', 'Category')], default='full_date', max_length=12, verbose_name='Permalink structure'),
        ),
    ]
